### ISSUE TITLE
Turn into package

### ISSUE THREAD

**Issue by dferber90** [tachyons-css/tachyons-styled-react#12]
🎈  First of all, this solution seems pretty great and I can't wait to play some more with it!

I wonder what the rationale behind a starter kit was compared to offering it as a package. If we turned this "starter-kit" into a package users could use plain `create-react-app` or any other setup instead and they would get bug fixes/updates.

I'm imagining a package (called `tachyons-emotion` below) which would allow users to do this:

### Setup

Install dependencies

```bash
yarn add tachyons-emotion styled-system @emotion/core emotion-theming # and some more
```

`tachyons-emotion` could have `emotion` & co as peer-dependencies and users would then provide `theme` as

```jsx
import { ThemeProvider } from "emotion-theming"
import { theme } from 'tachyons-emotion'

export default function App (props) {
  return (
    <ThemeProvider theme={theme}>
      <Router />
    </ThemeProvider>
  )
}
```

Users could still overwrite props of the theme by just spreading over it, or provide their own theme.

### Usage

```jsx
import { Section } from 'tachyons-emotion'

export default function Post() {
  return (<Section p={4}>Hello World</Section>);
}
```

This would allow using this Tachyons approach with Gatsby and customs solutions and not tie it to `create-react-app` at all. We could even keep this starter-repo alive by just using the `tachyons-emotion` package here.

### Bonus: Living Style Guide

We could even export a `Styles` component from `tachyons-emotion` which would render the complete styles as a living styleguide of sorts. Consumers could then render this component at a specific path.

```jsx
import { Styles } from 'tachyons-emotion'

export default function App() {
  return (
    <ThemeProvider theme={theme}>
      <Router>
        <Route path="/styles" component={Styles} />
      </Router>
    </ThemeProvider>
  )
}
```

Of course this could be improved to only include the component and route during development to keep the production bundle small.

If you're on board/think this is a good idea I could go ahead and create the repo, set things up and hand them over to you.

**Comment by mrmrs** [comment]
Few reasons behind the rationale to create it as a setup instead of a package. While there are pros to having it as a package there are also some cons. In this instance the pros don't cover any of my personal use cases. 

1. This is what I need / want for how I work. I just want to run yarn and yarn start and go.
2. This keeps all of the elements modifiable as I think they should be. So much harder for the end user to modify which props are passed in or what the default styles are. Also want you to have a setup where you can set different default styles per element per project if you want
3. Theme is also modifiable 
4. While this is largely for myself I do hope it is useful for a very particular audience: 
people who know html and css really well that want to try using css-in-js and react. I've tried to make it so it as little setup as possible. Don't know if building it as a package initially would help me lower that hurdle. 

The living style guide already exists as a component you can send to any route. Again keeping it inline here makes it a bit easier to customize the design / content of your living style guide. 

I have another setup on nextjs that is similar to this that I might open up but I'm not looking to maintain a bunch of stuff I don't use. Don't think tachyons-emotion is the appropriate name but If you'd like to create a package to reuse some of these patterns you can definitely feel free to do so - I am sure there are people who would find it useful. Thanks for the suggestion.

**Comment by dferber90** [comment]
Thanks for the in-depth response, really appreciate it! I get the rationale now :)

I might turn it into a package at some point so I can use the setup in a Gatsby app - but I need to play with it first to see if it's worth it.

**Comment by G-Ray** [comment]
I agree with @dferber90 that a package make sense. This way users can just import it and use it in any react.js project.

>  So much harder for the end user to modify which props are passed in or what the default styles are.

React's composability model should make this process painless. If a user wants to add a prop, they just need to create a new component which extends an existing one. The component which is extended should just have to accepts the new optional props, by writing something like this:
```js
<Comp {...optionalProps} />
```

I think we can add this to all the element from this project. What do you think about this ?

I just created https://github.com/G-Ray/tachyons-styled-system. It just re-exports the elements from this repo. If you have nothing against the name, I may publish it to npm.

**Comment by mrmrs** [comment]
@G-Ray Would prefer you don't use the name tachyons for your project.
